/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'inverse-primary': '#96ccff',
        'tertiary-fixed': '#ffdcc3',
        'on-tertiary-container': '#fffbff',
        'inverse-surface': '#2f312f',
        'on-error': '#ffffff',
        'primary-container': '#007abd',
        'on-tertiary-fixed': '#2f1500',
        'background': '#FAF9F6',
        'on-primary': '#ffffff',
        'surface': '#FAF9F6',
        'surface-container-lowest': '#ffffff',
        'surface-dim': '#dbdad7',
        'on-primary-fixed-variant': '#004a75',
        'surface-variant': '#e8e7e3',
        'error': '#ba1a1a',
        'surface-container-high': '#edece8',
        'outline': '#6f7882',
        'primary': '#006096',
        'on-primary-container': '#fdfcff',
        'secondary-fixed': '#d5e4fa',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#556477',
        'surface-container-low': '#f5f4f0',
        'primary-fixed': '#cee5ff',
        'on-background': '#111827',
        'error-container': '#ffdad6',
        'surface-tint': '#00639a',
        'tertiary-container': '#b15f00',
        'on-tertiary-fixed-variant': '#6e3900',
        'surface-bright': '#faf9f6',
        'tertiary': '#8d4b00',
        'on-secondary-fixed-variant': '#3a485a',
        'secondary-fixed-dim': '#b9c8dd',
        'primary-fixed-dim': '#96ccff',
        'on-secondary-fixed': '#0d1c2c',
        'secondary': '#516072',
        'tertiary-fixed-dim': '#ffb77d',
        'on-surface-variant': '#4b5563',
        'on-surface': '#111827',
        'on-tertiary': '#ffffff',
        'on-error-container': '#93000a',
        'on-primary-fixed': '#001d32',
        'secondary-container': '#d2e1f7',
        'surface-container': '#f0efe9',
        'inverse-on-surface': '#f2f1ee',
        'outline-variant': '#e2e8f0',
        'surface-container-highest': '#e5e4de',
      },
      borderRadius: {
        DEFAULT: '0.75rem',
        sm: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        '2xl': '2rem',
        '3xl': '2.5rem',
        full: '9999px',
      },
      spacing: {
        gutter: '1.5rem',
        'gutter-mobile': '1rem',
        'space-sm': '0.5rem',
        'space-xs': '0.25rem',
        'space-xl': '2.5rem',
        'space-md': '1rem',
        'margin-mobile': '1.25rem',
        'space-lg': '1.5rem',
        margin: '3rem',
      },
      fontFamily: {
        display: ['Space Grotesk', 'sans-serif'],
        'headline-lg': ['Space Grotesk', 'sans-serif'],
        'headline-md': ['Space Grotesk', 'sans-serif'],
        'headline-sm': ['Space Grotesk', 'sans-serif'],
        'headline-lg-mobile': ['Space Grotesk', 'sans-serif'],
        'display-mobile': ['Space Grotesk', 'sans-serif'],
        'label-lg': ['Space Grotesk', 'sans-serif'],
        'label-md': ['Space Grotesk', 'sans-serif'],
        'label-sm': ['Space Grotesk', 'sans-serif'],
        'body-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'body-md': ['Plus Jakarta Sans', 'sans-serif'],
        'body-sm': ['Plus Jakarta Sans', 'sans-serif'],
        sans: ['Plus Jakarta Sans', 'sans-serif'],
      },
      fontSize: {
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['15px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '500' }],
        'label-lg': ['14px', { lineHeight: '20px', fontWeight: '600' }],
        'headline-md': ['28px', { lineHeight: '36px', fontWeight: '500' }],
        'display-mobile': ['36px', { lineHeight: '44px', fontWeight: '600' }],
        'body-sm': ['13px', { lineHeight: '20px', fontWeight: '400' }],
        'headline-lg': ['40px', { lineHeight: '48px', fontWeight: '500' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        display: ['56px', { lineHeight: '64px', fontWeight: '600' }],
        'label-sm': ['10px', { lineHeight: '14px', fontWeight: '600' }],
        'label-md': ['12px', { lineHeight: '16px', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
};
